import { useEffect, useState } from "react";
import { request } from "../lib/api.js";
import SelectMenu from "../components/SelectMenu.jsx";

const token = () => { try { return JSON.parse(sessionStorage.getItem("melges-session"))?.token; } catch { return null; } };
const labels = { pending: "Em análise", accepted: "Aceito", rejected: "Recusado" };
const styles = { pending: "bg-amber-400/10 text-amber-300", accepted: "bg-emerald-400/10 text-emerald-300", rejected: "bg-red-400/10 text-red-300" };

function EditModal({ project, categories, onClose, onSaved }) {
  const [form, setForm] = useState({ name: project.name, description: project.description, features: project.features || "", categoryId: String(project.categoryId) });
  const [error, setError] = useState("");
  const save = async (event) => { event.preventDefault(); try { await request(`/admin/projects/${project.id}`, { method: "PATCH", body: JSON.stringify({ ...form, categoryId: Number(form.categoryId) }) }, token()); onSaved(); } catch (err) { setError(err.message); } };
  const field = "mt-2 w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 outline-none focus:border-violet";
  return <div className="fixed inset-0 z-[100] overflow-y-auto bg-black/70 p-4 backdrop-blur-sm sm:grid sm:place-items-center"><form onSubmit={save} className="mx-auto my-4 w-full max-w-2xl rounded-3xl border border-white/10 bg-ink-900 p-6 sm:p-8"><div className="flex justify-between"><div><span className="eyebrow">Administração</span><h2 className="mt-2 text-2xl font-bold">Editar projeto</h2></div><button type="button" onClick={onClose} className="text-2xl">×</button></div><div className="mt-6 grid gap-4"><label className="text-sm">Nome<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className={field} /></label><label className="text-sm">Descrição<textarea required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className={`${field} min-h-28`} /></label><label className="text-sm">Categoria<SelectMenu value={form.categoryId} options={categories} onChange={(id) => setForm({ ...form, categoryId: String(id) })} /></label><label className="text-sm">Funcionalidades<textarea value={form.features} onChange={(e) => setForm({ ...form, features: e.target.value })} className={`${field} min-h-20`} /></label></div>{error && <p className="mt-4 text-sm text-red-300">{error}</p>}<div className="mt-7 flex justify-end gap-3"><button type="button" className="btn-outline" onClick={onClose}>Cancelar</button><button className="btn-primary">Salvar alterações</button></div></form></div>;
}

function Progress({ value = 0, onSave }) { const [progress, setProgress] = useState(value); useEffect(() => setProgress(value), [value]); return <div className="rounded-xl border border-white/10 bg-white/[0.03] p-3"><div className="flex justify-between text-xs font-semibold uppercase tracking-wider text-white/40"><span>Desenvolvimento</span><b className="text-violet-light">{progress}%</b></div><input type="range" min="0" max="100" value={progress} onChange={(e) => setProgress(Number(e.target.value))} className="mt-3 w-full accent-violet" /><button type="button" onClick={() => onSave(progress)} className="mt-2 text-xs font-semibold text-violet-light hover:text-white">Salvar porcentagem</button></div>; }

export default function AdminPanel({ view = "overview" }) {
  const [data, setData] = useState({ projects: [], phases: [], categories: [] }); const [editing, setEditing] = useState(null); const [error, setError] = useState("");
  const load = async () => { try { setData(await request("/admin/projects", {}, token())); setError(""); } catch (err) { setError(err.message); } };
  useEffect(() => { load(); }, []);
  const update = async (id, path, body) => { try { await request(`/admin/projects/${id}/${path}`, { method: "PATCH", body: JSON.stringify(body) }, token()); load(); } catch (err) { setError(err.message); } };
  const pending = data.projects.filter((p) => p.approvalStatus === "pending").length; const accepted = data.projects.filter((p) => p.approvalStatus === "accepted").length; const projectsView = view === "projects" || view === "admin";
  return <section className="container-page py-12 sm:py-16"><span className="eyebrow">Área restrita</span><h1 className="mt-2 text-3xl font-bold sm:text-4xl">{projectsView ? "Todos os projetos" : "Visão geral administrativa"}</h1>{error && <p className="mt-4 text-sm text-red-300">{error}</p>}{!projectsView && <div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric label="Total" value={data.projects.length} /><Metric label="Em análise" value={pending} /><Metric label="Aceitos" value={accepted} /></div>}{projectsView && <div className="mt-8 space-y-4">{data.projects.map((project) => <article key={project.id} className="rounded-3xl border border-white/10 bg-white/[0.03] p-5"><div className="flex flex-col justify-between gap-5 lg:flex-row"><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-lg font-bold">{project.name}</h2><span className={`rounded-full px-3 py-1 text-xs font-semibold ${styles[project.approvalStatus]}`}>{labels[project.approvalStatus]}</span></div><p className="mt-2 text-sm text-white/50">{project.owner} · {project.category}</p><p className="mt-3 max-w-2xl text-sm text-white/65">{project.description}</p><button onClick={() => setEditing(project)} className="btn-outline mt-4 px-4 py-2 text-sm">Editar projeto</button></div><div className="flex flex-col gap-3 sm:min-w-60"><label className="text-xs font-semibold uppercase tracking-wider text-white/40">Fase de desenvolvimento<SelectMenu value={project.phaseId} options={data.phases} onChange={(id) => update(project.id, "phase", { phaseId: Number(id) })} /></label><Progress value={project.progressPercent} onSave={(progressPercent) => update(project.id, "progress", { progressPercent })} /><div className="flex gap-2">{project.approvalStatus !== "accepted" && <button onClick={() => update(project.id, "approval", { approvalStatus: "accepted" })} className="btn-primary flex-1 px-3 py-2">Aceitar</button>}{project.approvalStatus !== "rejected" && <button onClick={() => update(project.id, "approval", { approvalStatus: "rejected" })} className="btn-outline flex-1 px-3 py-2">Recusar</button>}</div></div></div></article>)}</div>}{editing && <EditModal project={editing} categories={data.categories} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); load(); }} />}</section>;
}
function Metric({ label, value }) { return <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><p className="text-sm text-white/50">{label}</p><p className="mt-2 text-3xl font-bold text-violet-light">{value}</p></div>; }
