import { useState } from "react";
import { request } from "../lib/api.js";
import logotipo from "../assets/logotipo.svg";

const SESSION_KEY = "melges-session";
export function getStoredSession() { try { const session = JSON.parse(sessionStorage.getItem(SESSION_KEY)); return session?.token && session?.user ? session.user : null; } catch { return null; } }

export default function AuthPage({ onAuthenticated, onBack }) {
  const [mode, setMode] = useState("login");
  const [form, setForm] = useState({ username: "", name: "", email: "", phone: "", company: "", password: "" });
  const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const change = (key, value) => setForm({ ...form, [key]: value });
  const submit = async (event) => { event.preventDefault(); setError(""); setLoading(true); try { const body = mode === "register" ? form : { email: form.email, password: form.password }; const result = await request(`/auth/${mode === "register" ? "register" : "login"}`, { method: "POST", body: JSON.stringify(body) }); sessionStorage.setItem(SESSION_KEY, JSON.stringify(result)); onAuthenticated(result.user); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  const input = "mt-2 w-full rounded-xl border border-white/10 bg-white/[0.06] px-4 py-3 text-white shadow-inner outline-none transition placeholder:text-white/25 focus:border-violet focus:bg-white/[0.09]";
  return <div className="fixed inset-0 z-[100] overflow-y-auto bg-ink-950/80 px-4 py-4 backdrop-blur-md sm:grid sm:place-items-center sm:px-6 sm:py-10"><section className="relative mx-auto w-full max-w-md rounded-[2rem] border border-white/10 bg-ink-900 p-6 shadow-[0_30px_90px_rgba(0,0,0,.55)] sm:p-9"><div className="flex items-center justify-between"><img src={logotipo} alt="Melges" className="h-7 w-auto" /><button type="button" onClick={onBack} className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-white/55 hover:bg-white/5 hover:text-white">Fechar</button></div><div className="mt-7 rounded-2xl border border-white/10 bg-black/15 p-1"><button type="button" onClick={() => setMode("login")} className={`w-1/2 rounded-xl py-2 text-sm font-semibold ${mode === "login" ? "bg-violet text-white" : "text-white/45"}`}>Entrar</button><button type="button" onClick={() => setMode("register")} className={`w-1/2 rounded-xl py-2 text-sm font-semibold ${mode === "register" ? "bg-violet text-white" : "text-white/45"}`}>Cadastrar</button></div><span className="eyebrow mt-7 block">Área exclusiva</span><h1 className="mt-2 text-2xl font-bold sm:text-3xl">{mode === "login" ? "Bem-vinda de volta" : "Crie sua conta"}</h1><p className="mt-2 text-sm text-white/50">{mode === "login" ? "Acesse seus projetos e acompanhe cada etapa." : "Cadastre-se para enviar e acompanhar seus projetos."}</p><form className="mt-6 flex flex-col gap-3" onSubmit={submit}>{mode === "register" && <><label className="text-sm text-white/75">Nome de usuário<input required value={form.username} onChange={(e) => change("username", e.target.value)} className={input} /></label><label className="text-sm text-white/75">Nome completo<input required value={form.name} onChange={(e) => change("name", e.target.value)} className={input} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm text-white/75">Empresa<input value={form.company} onChange={(e) => change("company", e.target.value)} className={input} /></label><label className="text-sm text-white/75">Telefone<input value={form.phone} onChange={(e) => change("phone", e.target.value)} className={input} /></label></div></>}<label className="text-sm text-white/75">E-mail<input required type="email" value={form.email} onChange={(e) => change("email", e.target.value)} className={input} /></label><label className="text-sm text-white/75">Senha<input required minLength="8" type="password" value={form.password} onChange={(e) => change("password", e.target.value)} className={input} /></label>{error && <p className="rounded-xl border border-red-400/30 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}<button className="btn-primary mt-3 w-full" disabled={loading}>{loading ? "Aguarde..." : mode === "login" ? "Entrar no painel" : "Criar minha conta"}</button></form></section></div>;
}
