type User @table {
  username: String!
  email: String!
  password: String!
  isAdmin: Boolean @default(value: false)
  createdAt: Timestamp
  updatedAt: Timestamp
}

type Category @table {
  name: String!
  description: String
  createdAt: Timestamp
  updatedAt: Timestamp
}

type Phase @table {
  name: String!
  description: String
  createdAt: Timestamp
  updatedAt: Timestamp
}

type Project @table {
  name: String!
  description: String
  user: User!
  category: Category!
  phase: Phase!
  createdAt: Timestamp
  updatedAt: Timestamp
}

type AuditLog @table {
  user: User!
  project: Project!
  createdAt: Timestamp
  updatedAt: Timestamp
}
